// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WEB_API_KEY']!,
    appId: '1:236515048151:web:1f7a243601db9f2df6ce92',
    messagingSenderId: '236515048151',
    projectId: 'menuapp-f612a',
    authDomain: 'menuapp-f612a.firebaseapp.com',
    storageBucket: 'menuapp-f612a.appspot.com',
    measurementId: 'G-F2N06RGVC4',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROID_API_KEY']!,
    appId: '1:236515048151:android:bc18fc26361dcbf3f6ce92',
    messagingSenderId: '236515048151',
    projectId: 'menuapp-f612a',
    storageBucket: 'menuapp-f612a.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['MACOS_API_KEY']!,
    appId: '1:236515048151:ios:de109e4103a4623df6ce92',
    messagingSenderId: '236515048151',
    projectId: 'menuapp-f612a',
    storageBucket: 'menuapp-f612a.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['MACOS_API_KEY']!,
    appId: '1:236515048151:ios:d5113dd8915f6e02f6ce92',
    messagingSenderId: '236515048151',
    projectId: 'menuapp-f612a',
    storageBucket: 'menuapp-f612a.appspot.com',
    iosBundleId: 'com.example.finalProject.RunnerTests',
  );
}
